# Generated by Django 2.1.11 on 2019-10-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affirmationapp', '0002_auto_20191004_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='taskitem',
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='media_users', to='affirmationapp.User'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_users', to='affirmationapp.User'),
        ),
    ]
