# Generated by Django 2.1.11 on 2019-10-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affirmationapp', '0003_auto_20191009_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.CharField(max_length=3000),
        ),
    ]
